"use client";
import {FormEvent,Suspense,useState} from "react";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {getCluster,getRecord,getCorrection} from "@/lib/genlayer/data-source";
import {loadClusterCorrections} from "@/lib/live-loaders";
import {useLive} from "@/lib/use-live";
import {useContractWrite} from "@/lib/use-write";
import {LoadingState,Unavailable} from "@/components/states";
import {AccessionCard} from "@/components/accession-card";
import {TransactionRail} from "@/components/transaction-rail";
import type {CorrectionCase} from "@/lib/contract-types";

function NewCorrectionInner(){
 const q=useSearchParams();const clusterId=Number(q.get("cluster")),recordId=Number(q.get("record"));const tx=useContractWrite();const [cid,setCid]=useState<number>();const[row,setRow]=useState<CorrectionCase>();
 const live=useLive(async()=>{if(!Number.isInteger(clusterId)||clusterId<1||!Number.isInteger(recordId)||recordId<1)throw new Error("Valid cluster and record query parameters are required");const[c,r]=await Promise.all([getCluster(clusterId),getRecord(recordId)]);if(c.kind!=="AVAILABLE"||r.kind!=="AVAILABLE")throw new Error("Live cluster and record are required");if(c.value.superseded_by)throw new Error(`Cluster ${clusterId} is superseded by cluster ${c.value.superseded_by}`);if(r.value.cluster_id!==clusterId)throw new Error("The record is not an active member of this cluster");return{cluster:c.value,record:r.value}},[clusterId,recordId]);
 async function discover(){const rows=await loadClusterCorrections(clusterId);for(const c of [...rows].reverse()){if(c.record_id===recordId){setCid(c.id);setRow(c);return;}}}
 async function propose(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await tx.run("propose_correction",[BigInt(clusterId),BigInt(recordId),String(f.get("url")||"").trim(),String(f.get("digest")||"").trim()],discover)}catch{}}
 async function adjudicate(){if(!cid)return;try{await tx.run("adjudicate_correction",[BigInt(cid)],async()=>{const c=await getCorrection(cid);if(c.kind==="AVAILABLE")setRow(c.value)})}catch{}}
 async function invalidate(){if(!cid)return;try{await tx.run("invalidate_stale_correction",[BigInt(cid)],async()=>{const c=await getCorrection(cid);if(c.kind==="AVAILABLE")setRow(c.value)})}catch{}}
 if(live.loading)return <main className="page"><LoadingState label="Opening correction folio"/></main>;if(live.error||!live.data)return <main className="page"><Unavailable message={live.error??"Correction context unavailable"}/></main>;
 return <main className="page correction-page"><header className="folio-heading"><span className="eyebrow">VERSIONED CORRECTION</span><h1>Challenge cluster membership</h1><p>A prior merge receipt is never erased. A successful challenge changes current membership, increments the cluster version, and leaves both decisions in provenance.</p></header><div className="correction-layout"><AccessionCard record={live.data.record}/><section className="correction-note"><span>ACTIVE CLUSTER</span><h2>{live.data.cluster.canonical_label}</h2><p>Cluster {clusterId} · version {live.data.cluster.version} · {live.data.cluster.member_count} active records</p><Link href={`/entities/${clusterId}`}>Back to dossier</Link></section></div>{!cid?<form className="evidence-ticket" onSubmit={propose}><label>Public correction evidence URL<input name="url" type="url" required/></label><label>Evidence SHA-256 digest<input name="digest" required/></label><p className="form-note">The proposal freezes the selected peer-record IDs. Later registrations cannot silently change which cluster context validators judge. DETACH_MEMBER requires affirmative contradiction across at least two identity-anchor categories and independent validator agreement.</p><button className="seal-button" disabled={!tx.canWrite}>Propose correction</button></form>:<section className="decision-desk"><span className="ticket-no">CORRECTION {String(cid).padStart(5,"0")}</span><h2>{row?.decision||"Pending correction adjudication"}</h2>{row?.decision?<Link className="press-button" href={`/corrections/${cid}`}>Open correction receipt</Link>:<><p>The proposal-time peer set is frozen. If cluster membership or version changed afterward, close this correction as stale rather than evaluating a different entity state.</p><div className="box-actions"><button className="seal-button" disabled={!tx.canWrite} onClick={adjudicate}>Run correction consensus</button><button type="button" disabled={!tx.canWrite} onClick={invalidate}>Close only if stale</button></div></>}</section>}<TransactionRail stage={tx.stage} hash={tx.hash} message={tx.message}/></main>
}
export default function NewCorrection(){return <Suspense fallback={<main className="page"><div className="folio-state">Opening correction folio…</div></main>}><NewCorrectionInner/></Suspense>}
