"use client";
import Link from "next/link";
import {FormEvent,useState} from "react";
import {useParams} from "next/navigation";
import {AccessionCard} from "@/components/accession-card";
import {TransactionRail} from "@/components/transaction-rail";
import {LoadingState,Unavailable} from "@/components/states";
import {getCase,getRecord} from "@/lib/genlayer/data-source";
import {loadArchiveCases} from "@/lib/live-loaders";
import {useLive} from "@/lib/use-live";
import {useContractWrite} from "@/lib/use-write";
import type {ResolutionCase} from "@/lib/contract-types";

export default function ResolvePage(){
 const p=useParams<{a:string;b:string}>();const aId=Number(p.a),bId=Number(p.b);const tx=useContractWrite();const [caseId,setCaseId]=useState<number>();const [caseRow,setCaseRow]=useState<ResolutionCase>();const[formError,setFormError]=useState<string>();
 const pair=useLive(async()=>{if(!Number.isInteger(aId)||aId<1||!Number.isInteger(bId)||bId<1)throw new Error("Valid positive record IDs are required");const[a,b]=await Promise.all([getRecord(aId),getRecord(bId)]);if(a.kind!=="AVAILABLE"||b.kind!=="AVAILABLE")throw new Error("Both live records are required");if(a.value.archive_id!==b.value.archive_id)throw new Error("Records belong to different archives");return{a:a.value,b:b.value,archiveId:a.value.archive_id}},[aId,bId]);
 async function discover(){if(!pair.data)return;const rows=await loadArchiveCases(pair.data.archiveId);for(const c of [...rows].reverse()){if((c.record_a===aId&&c.record_b===bId)||(c.record_a===bId&&c.record_b===aId)){setCaseId(c.id);setCaseRow(c);return;}}}
 async function propose(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!pair.data)return;setFormError(undefined);const f=new FormData(e.currentTarget);const evidenceUrl=String(f.get("evidenceUrl")||"").trim();const digest=String(f.get("digest")||"").trim();if(Boolean(evidenceUrl)!==Boolean(digest)){setFormError("Additional evidence is optional, but URL and SHA-256 digest must be supplied together.");return;}try{await tx.run("propose_resolution",[BigInt(pair.data.archiveId),BigInt(aId),BigInt(bId),evidenceUrl,digest],discover);}catch{}}
 async function adjudicate(){if(!caseId)return;try{await tx.run("adjudicate_resolution",[BigInt(caseId)],async()=>{const c=await getCase(caseId);if(c.kind==="AVAILABLE")setCaseRow(c.value);});}catch{}}
 async function invalidate(){if(!caseId)return;try{await tx.run("invalidate_stale_resolution",[BigInt(caseId)],async()=>{const c=await getCase(caseId);if(c.kind==="AVAILABLE")setCaseRow(c.value);});}catch{}}
 if(pair.loading)return <main className="page"><LoadingState label="Placing accession cards on the comparison table"/></main>;if(pair.error||!pair.data)return <main className="page"><Unavailable message={pair.error??"Pair unavailable"}/></main>;
 const sameActiveCluster=pair.data.a.cluster_id>0&&pair.data.a.cluster_id===pair.data.b.cluster_id;
 return <main className="page resolve-page"><header className="folio-heading"><span className="eyebrow">IDENTITY RESOLUTION LIGHT TABLE</span><h1>Compare public records</h1><p>Similarity brought these cards together. It does not decide what they mean. Validators independently fetch digest-bound sources before any cluster can change.</p></header><section className="comparison-table"><AccessionCard record={pair.data.a}/><div className="identity-axis"><span>A</span><i/><strong>?</strong><i/><span>B</span></div><AccessionCard record={pair.data.b}/></section>
 {sameActiveCluster?<section className="decision-desk"><span className="ticket-no">ACTIVE ENTITY {pair.data.a.cluster_id}</span><h2>These records already share canonical membership.</h2><p>A second pairwise resolution could contradict current canonical state. Use the versioned correction path to challenge a member instead; the prior merge receipt will remain in lineage.</p><div className="box-actions"><Link className="press-button" href={`/entities/${pair.data.a.cluster_id}`}>Open entity dossier</Link><Link href={`/corrections/new?cluster=${pair.data.a.cluster_id}&record=${aId}`}>Challenge record A membership</Link></div></section>:!caseId?<form className="evidence-ticket" onSubmit={propose}><div><span className="ticket-no">RESOLUTION TICKET</span><h2>Freeze the comparison case</h2><p>Additional evidence is optional. If supplied, both URL and SHA-256 digest are frozen with the case.</p></div><label>Additional public evidence URL<input name="evidenceUrl" type="url" placeholder="https://…"/></label><label>Evidence SHA-256<input name="digest" placeholder="Required only when URL is supplied"/></label>{formError?<p className="form-note" role="alert">{formError}</p>:null}<WriteGate tx={tx}/><button className="seal-button" disabled={!tx.canWrite}>Propose resolution</button></form>:<section className="decision-desk"><span className="ticket-no">CASE {String(caseId).padStart(5,"0")}</span><h2>{caseRow?.relation||"Pending semantic adjudication"}</h2>{caseRow?.relation?<><p>{caseRow.rationale}</p><Link className="press-button" href={`/cases/${caseId}`}>Open immutable receipt</Link></>:<><p>The case is frozen. Adjudication will use the proposal-time VecDB candidate context and run independent source-grounded validator judgment. If cluster state changed after proposal, close the case as stale instead of forcing obsolete evidence through consensus.</p><div className="box-actions"><button className="seal-button" disabled={!tx.canWrite} onClick={adjudicate}>Run consensus adjudication</button><button type="button" disabled={!tx.canWrite} onClick={invalidate}>Close only if stale</button></div></>}</section>}
 <TransactionRail stage={tx.stage} hash={tx.hash} message={tx.message}/></main>
}
function WriteGate({tx}:{tx:ReturnType<typeof useContractWrite>}){return !tx.canWrite?<div className="write-gate"><strong>Signature gate</strong><span>{tx.writeBlockedReason}</span>{tx.network==="wrong"?<button type="button" onClick={tx.switchNetwork}>Switch to StudioNet</button>:!tx.address?<button type="button" onClick={tx.connect}>Connect wallet</button>:null}</div>:<div className="write-gate ready"><strong>Ready</strong><span>Injected wallet · StudioNet 61999</span></div>}
