"use client";
import Link from "next/link";
import type { CSSProperties } from "react";
import { useParams } from "next/navigation";
import { loadCluster, loadClusterMembers, loadClusterCases, loadClusterCorrections } from "@/lib/live-loaders";
import { useLive } from "@/lib/use-live";
import { AccessionCard } from "@/components/accession-card";
import { LoadingState, Unavailable } from "@/components/states";
import { caseStatus, correctionStatus } from "@/lib/contract-types";
export default function EntityPage(){const id=Number(useParams<{clusterId:string}>().clusterId);const bundle=useLive(async()=>{const cluster=await loadCluster(id);const [members,cases,corrections]=await Promise.all([loadClusterMembers(id),loadClusterCases(id),loadClusterCorrections(id)]);return{cluster,members,cases,corrections};},[id]);if(bundle.loading)return <main className="page"><LoadingState label="Assembling entity dossier"/></main>;if(bundle.error||!bundle.data)return <main className="page"><Unavailable message={bundle.error??"Entity cluster unavailable"}/></main>;const {cluster,members,cases,corrections}=bundle.data;return <main className="page entity-page"><header className="dossier-heading"><div className="entity-seal">ENTITY<br/>AF-{String(id).padStart(4,"0")}</div><div><span className="eyebrow">{cluster.entity_type} · VERSION {cluster.version}</span><h1>{cluster.canonical_label}</h1><p>{cluster.member_count} active accession record{cluster.member_count===1?"":"s"}. Original records remain individually addressable.</p></div><div className="dossier-actions"><Link href={`/clusters/${id}/lineage`}>Open lineage</Link>{cluster.superseded_by?<Link href={`/entities/${cluster.superseded_by}`}>Follow superseding cluster →</Link>:null}</div></header><section className="member-folio"><h2>Active accession cards</h2><div className="fanned-cards">{members.map((r,i)=><div className="fan" style={{"--fan":i} as CSSProperties} key={r.id}><AccessionCard record={r}/>{members.length>1?<Link className="correction-link" href={`/corrections/new?cluster=${id}&record=${r.id}`}>Challenge membership</Link>:null}</div>)}</div></section><section className="provenance-ledger"><div><h2>Resolution provenance</h2>{cases.length?cases.map(c=><Link className="ledger-entry" href={`/cases/${c.id}`} key={c.id}><span>CASE {String(c.id).padStart(4,"0")}</span><strong>{caseStatus(c.status)}</strong><small>{c.record_a} ↔ {c.record_b}</small></Link>):<p className="muted">No case receipts returned.</p>}</div><div><h2>Correction provenance</h2>{corrections.length?corrections.map(c=><Link className="ledger-entry" href={`/corrections/${c.id}`} key={c.id}><span>CORR {String(c.id).padStart(4,"0")}</span><strong>{correctionStatus(c.status)}</strong><small>Record {c.record_id}</small></Link>):<p className="muted">No correction receipts.</p>}</div></section></main>}
